// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {todo} from '../models';
import {uuid} from '../models';

export function CreateTodo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListTodos():Promise<Array<todo.Entity>>;

export function UpdateTodo(arg1:uuid.UUID,arg2:string,arg3:string,arg4:string):Promise<void>;
